version: '3.5'

networks:
  yp_network:
    name: yp_network
    external: true

services:
  backend:
    build:
      context: ../../
      dockerfile: devops/docker/admin/Dockerfile
    env_file:
      - ../admin/.env
    volumes:
      - ../../../src/admin/static:/admin/static/
    networks:
      - yp_network

  nginx:
    image: nginx:1.23.1
    volumes:
      - ../admin/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../admin/nginx/conf.d/:/etc/nginx/conf.d
      - ../../src/admin/static:/data/static/
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - yp_network
