version: '3.5'

networks:
  yp_network:
    name: yp_network
    external: true

services:
    worker-mailer:
      container_name: worker-mailer
      hostname: worker-mailer
      build:
        context: devops/worker
        args:
          uid: ${HOST_UID}
          gid: ${HOST_GID}
      env_file:
        - .env
      entrypoint: 'tail -F anything'

    worker-chunker-background:
      container_name: worker-chunker-background
      hostname: worker-chunker-background
      build:
        context: devops/worker
      env_file:
        - .env
      entrypoint: 'python3 /usr/src/worker/workers/chunker.py --background'

    worker-chunker-realtime:
      container_name: worker-chunker-realtime
      hostname: worker-chunker-realtime
      build:
        context: devops/worker
      env_file:
        - .env
      entrypoint: 'python3 /usr/src/worker/chunker.py --realtime'
