version: '3.5'

# в окружении разработчика стенд использует локальные службы rabbit и postgres
# dev окружение самодостаточно для stand-alone тестирования

services:
    worker-chunker-realtime:
      depends_on:
        - worker-rabbitmq
      build:
        target: develop
      volumes:
        - ../../src/:/usr/src
        - ../../lib/:/usr/lib
        - ../../test/:/usr/test
      env_file:
        - .env
        - ../rabbitmq/.env

    worker-chunker-background:
      depends_on:
        - worker-rabbitmq
      build:
        target: develop
      volumes:
        - ../../src/:/usr/src
        - ../../lib/:/usr/lib
        - ../../test/:/usr/test
      env_file:
        - .env
        - ../rabbitmq/.env

    worker-mailer:
      depends_on:
        - worker-mailhog
        - worker-rabbitmq
      build:
        target: develop
      volumes:
        - ../../src/:/usr/src
        - ../../lib/:/usr/lib
        - ../../test/:/usr/test
      env_file:
        - .env
        - ../rabbitmq/.env
    worker-rabbitmq:
      container_name: worker-rabbitmq
      hostname: worker-rabbitmq
      image: rabbitmq:3.10.5-management-alpine
      ports:
        - 5672:5672
        - 15672:15672
      volumes:
        - rabbitmq_data:/var/lib/rabbitmq/
      env_file:
        - .env
        - ../rabbitmq/.env

    worker-mailhog:
      container_name: mailhog_notification
      image: mailhog/mailhog
      logging:
        driver: 'none'
      ports:
        - 1025:1025
        - 8025:8025

volumes:
    rabbitmq_data:
