# Generated by Django 4.1.5 on 2023-01-18 06:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="templateusergroup",
            name="template",
        ),
        migrations.RemoveField(
            model_name="templateusergroup",
            name="user_group",
        ),
        migrations.RemoveField(
            model_name="usergroupthrough",
            name="user",
        ),
        migrations.RemoveField(
            model_name="usergroupthrough",
            name="user_group",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="user_group",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="user_group",
        ),
        migrations.RemoveField(
            model_name="template",
            name="user_group",
        ),
        migrations.DeleteModel(
            name="NotificationUserGroup",
        ),
        migrations.DeleteModel(
            name="TemplateUserGroup",
        ),
        migrations.DeleteModel(
            name="UserGroup",
        ),
        migrations.DeleteModel(
            name="UserGroupThrough",
        ),
        migrations.AddField(
            model_name="customuser",
            name="user_group",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("all", "All"),
                        ("monthly", "Monthly"),
                        ("weekly", "Weekly"),
                        ("daily", "Daily"),
                    ],
                    default="all",
                    max_length=255,
                ),
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="user_group",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("all", "All"),
                        ("monthly", "Monthly"),
                        ("weekly", "Weekly"),
                        ("daily", "Daily"),
                    ],
                    default="all",
                    max_length=255,
                ),
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="user_group",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("all", "All"),
                        ("monthly", "Monthly"),
                        ("weekly", "Weekly"),
                        ("daily", "Daily"),
                    ],
                    default="all",
                    max_length=255,
                ),
                default=list,
                size=None,
            ),
        ),
    ]
