# Generated by Django 4.1.5 on 2023-01-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_remove_templateusergroup_template_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[("instant", "Instant"), ("scheduled", "Scheduled")],
                default="instant",
                max_length=256,
                verbose_name="type",
            ),
        ),
    ]
