@startuml

'https://plantuml.com/use-case-diagram'
skinparam actorStyle awesome
!theme toy


actor Manager
actor Client
actor User

package "Notification API" {
    "New UGC content" as (Reaction)
    "Schedule periodic notifications" as (Periodic)
    "Send immediate notification" as (Notification)
    "Configure client notifications" as (Account)

}

'''Это черновик, дальше UGC убрать и заменить на Admin Panel"
package "UGC" {
    component FastAPI as ugc_gate
    database Kafka as ugc_kafka
    component ETL as ugc_etl
    database ClickHouse as ugc_clickhouse
}


User ..> (Notification)
User ..> (Reaction)
User <..> ugc_gate

Client ..> (Notification)
Client ..> (Account)

Manager ..> (Periodic)
Manager ..> (Notification)

ugc_gate --> ugc_kafka: save events
ugc_kafka <-- ugc_etl: extract events
ugc_etl --> ugc_clickhouse: upload events

@enduml
