@startuml "Notifications worker module"
!theme toy
'''Часть сервиса уведомлений, отвечающая за доставку уведомлений в каналы распространения''


'''Хранилища и внешние сервисы'''
cloud "notifications: Queue" {
    database "rabbitmq" {
        [Realtime queue]
        [Background queue]
    }
}

cloud "notifications: Storage" {
    database "postgres" {
        [Notifications config]

    }
}


'''Компоненты бизнес-логики'''
component "Worker: Service" {
    'Внешние интерфейсы службы'
    portin rabbit.queue
    portin postgres.rw
    portout admin.http

    'Компоненты службы'
    [Queue Manager]
    note right of [Queue Manager]: Delivery & rate-limiting


    package "Workers" {
        [Controller]
        [Email Worker]
        [Push Worker]
    }

    package "Async Sub-Service" {
        [Policy Manager]
        note bottom of [Policy Manager]: Pre-send policy checks

        [Enricher]
        note bottom of [Enricher]: Final content personalization
    }

    'Внутренние каналы службы'
    [Queue Manager] --> [Controller]
    [Queue Manager] <-> [Policy Manager]
    [Queue Manager] <-> [Enricher]

    [Controller] --> [Email Worker]
    [Controller] --> [Push Worker]

    'Обслуживание внешних интерфейсы'
    rabbit.queue -->  [Queue Manager]
    postgres.rw  <--  [Policy Manager]
    
    [Enricher] <-> admin.http
}


'''Обслуживание внешних и облачных сервисов'''
[Background queue] ..> rabbit.queue
[Realtime queue]   ..> rabbit.queue
[Notifications config] .down.> postgres.rw

@enduml
