version: '3.5'

networks:
  yp_network:
    name: yp_network
    external: true

services:
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-main
    hostname: kafka-main
    env_file:
      - .env
    depends_on:
      - zookeeper
    networks:
      - yp_network

  zookeeper:
    image: zookeeper:3.5
    container_name: kafka-zookeeper
    hostname: kafka-zookeeper
    networks:
      - yp_network
