# Generated by Django 4.0.3 on 2022-04-09 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_rename_film_work_id_personfilmwork_film_work_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="genrefilmwork",
            old_name="film_work_id",
            new_name="film_work",
        ),
        migrations.RenameField(
            model_name="genrefilmwork",
            old_name="genre_id",
            new_name="genre",
        ),
    ]
