# Generated by Django 4.0.3 on 2022-04-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_rename_created_filmwork_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="filmwork",
            name="file_path",
            field=models.FileField(
                blank=True, null=True, upload_to="movies/", verbose_name="file"
            ),
        ),
    ]
