# Generated by Django 4.0.3 on 2022-04-09 18:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0006_alter_filmwork_creation_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="genrefilmwork",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created_at",
            ),
            preserve_default=False,
        ),
    ]
