# Generated by Django 4.0.3 on 2022-04-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0007_genrefilmwork_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="genre",
            name="role",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="role"
            ),
        ),
    ]
