# Generated by Django 4.0.3 on 2022-04-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0009_personfilmwork_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="personfilmwork",
            name="role",
            field=models.CharField(
                default="extras", max_length=255, verbose_name="role"
            ),
            preserve_default=False,
        ),
    ]
