# Generated by Django 4.0.3 on 2022-04-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0010_personfilmwork_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filmwork",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="genre",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
    ]
