# Generated by Django 4.0.3 on 2022-04-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0011_alter_filmwork_description_alter_genre_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personfilmwork",
            name="role",
            field=models.CharField(
                choices=[
                    ("actor", "Actor"),
                    ("director", "Director"),
                    ("extras", "Extras"),
                    ("screenwriter", "Screenwriter"),
                ],
                max_length=255,
                verbose_name="role",
            ),
        ),
        migrations.AddIndex(
            model_name="genrefilmwork",
            index=models.Index(
                fields=["genre", "film_work"], name="film_work_creation_date"
            ),
        ),
        migrations.AddIndex(
            model_name="personfilmwork",
            index=models.Index(
                fields=["person", "film_work"], name="person_film_work_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="genrefilmwork",
            constraint=models.UniqueConstraint(
                fields=("film_work", "genre"),
                include=("created_at",),
                name="unique_film_genre",
            ),
        ),
        migrations.AddConstraint(
            model_name="personfilmwork",
            constraint=models.UniqueConstraint(
                fields=("person", "film_work", "role"),
                include=("person", "film_work"),
                name="unique_person_role_film",
            ),
        ),
    ]
