# Generated by Django 4.0.4 on 2022-04-21 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0013_alter_personfilmwork_role"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="personfilmwork",
            options={"verbose_name": "person", "verbose_name_plural": "person"},
        ),
        migrations.AlterField(
            model_name="personfilmwork",
            name="film_work",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.filmwork",
                verbose_name="movie",
            ),
        ),
        migrations.AlterField(
            model_name="personfilmwork",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.person",
                verbose_name="person",
            ),
        ),
    ]
