# Generated by Django 4.0.4 on 2022-04-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0015_person_birth_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genre",
            name="role",
        ),
        migrations.AlterField(
            model_name="personfilmwork",
            name="role",
            field=models.CharField(
                choices=[
                    ("actor", "Actor"),
                    ("director", "Director"),
                    ("writer", "Screenwriter"),
                ],
                max_length=255,
                verbose_name="role",
            ),
        ),
    ]
