# Generated by Django 4.0.4 on 2022-05-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0016_remove_genre_role_alter_personfilmwork_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="genrefilmwork",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="personfilmwork",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
